version: '3.9'

# ðŸ” Variables de entorno compartidas
x-shared-environment: &shared-env
  JWT_SIGNING_KEY: "super-secret-signing-key-shared-between-services"

services:
  task-core-service:
    build:
      context: ./task-core-service
    container_name: task-core-service
    ports:
      - "8000:8000"
    volumes:
      - ./task-core-service:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - stats-load-balancer
      - auth-service
    environment:
      <<: *shared-env

  task-stats-service-1:
    build:
      context: ./task-stats-service
    container_name: task-stats-service-1
    volumes:
      - ./task-stats-service:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    environment:
      <<: *shared-env

  task-stats-service-2:
    build:
      context: ./task-stats-service
    container_name: task-stats-service-2
    volumes:
      - ./task-stats-service:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    environment:
      <<: *shared-env

  stats-load-balancer:
    build:
      context: ./stats-load-balancer
    container_name: stats-load-balancer
    ports:
      - "8001:80"
    depends_on:
      - task-stats-service-1
      - task-stats-service-2

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: >
      "
      sleep 10 &&
      kafka-topics --create --topic task-events --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1
      "

  task-stats-consumer:
    build:
      context: ./task-stats-service
    container_name: task-stats-consumer
    depends_on:
      - kafka
      - task-stats-service-1
    command: python manage.py start_consumer
    environment:
      <<: *shared-env

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8002:8002"
    volumes:
      - ./auth-service:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    environment:
      <<: *shared-env